DELETE FROM ROAD;
DELETE FROM LOCATION;
DELETE FROM PROJECT;

CREATE TABLE ROAD(
    UNIQUE_ROAD_IDENTIFIER VARCHAR(255),
    ROAD_NAME VARCHAR(255), 
    DESCRIPTION VARCHAR(255),
    LENGTH_IN_KILOMETERS NUMBER(38),
    CATEGORY_ID VARCHAR(255),
    START_LOCATION_ID VARCHAR(255),
    END_LOCATION_ID VARCHAR(255),
    
    PRIMARY KEY (UNIQUE_ROAD_IDENTIFIER),
    FOREIGN KEY (CATEGORY_ID) REFERENCES CATEGORY(CATEGORY_ID)
);


CREATE TABLE LOCATION(
    LOCATION_ID VARCHAR(255),
    LOCATION_NAME VARCHAR(255),
    LATITUDE NUMBER(10),
    LONGITUDE NUMBER(10),
    DESCRIPTION VARCHAR(255),
    
    PRIMARY KEY(LOCATION_ID)
);

CREATE TABLE PROJECT(
    PROJECT_CODE VARCHAR(255),
    PROJECT_NAME VARCHAR(255),
    DESCRIPTION VARCHAR(255),
    DATE_START DATE,
    DATE_COMPLETE DATE,
    ROAD_ID VARCHAR(255),
    
    PRIMARY KEY(PROJECT_CODE),
    FOREIGN KEY (ROAD_ID) REFERENCES ROAD(ROAD_ID)
);

CREATE TABLE CATEGORY(
    CATEGORY_ID VARCHAR(255),
    CATEGORY_NAME VARCHAR(255),
    
    PRIMARY KEY(CATEGORY_ID)
);

CREATE TABLE CONTRACT_MANAGER(
    MANAGER_ID VARCHAR(255),
    START_DATE_FOR_CONTRACT DATE,
    END_DATE_FOR_CONTRACT DATE,
    EMPLOYEE_ID VARCHAR(255),
    
    PRIMARY KEY(MANAGER_ID)
    --FOREIGN KEY (EMPLOYEE_ID) REFERENCES CONTRACT(CONTRACT_NUMBER)
);

CREATE TABLE CONTRACT(
    CONTRACT_NUMBER VARCHAR(255),
    CONTRACT_NAME VARCHAR(255),
    DESCRIPTION VARCHAR(255),
    ESTIMATED_COST NUMBER(35),
    ACTUAL_COST NUMBER(35),
    DATE_STARTED DATE,
    DATE_ENDED DATE,
    PROJECT_CODE VARCHAR(255),
    CONTRACTOR_COMPANY_NAME VARCHAR(255),
    CONTRACT_MANAGER_ID VARCHAR(255),
    
    PRIMARY KEY(CONTRACT_NUMBER)
);

CREATE TABLE STAFF_MEMBER(
    EMPLOYEE_ID VARCHAR(255),
    FIRST_NAME VARCHAR(255),
    LAST_NAME VARCHAR(255),
    DATE_FIRST_EMPLOYED DATE,
    DATE_OF_BIRTH DATE,
    GENDER VARCHAR(255),
    POSTAL_ADDRESS VARCHAR(255),
    CONTRACT_PHONE_NUMBER VARCHAR(255),
    EMAIL_ADDRESS VARCHAR(255),
    
    PRIMARY KEY(EMPLOYEE_ID)
);

CREATE TABLE ROLE_(
    ROLE_ID VARCHAR(255),
    ROLE_NAME VARCHAR(255),
    DESCRIPTION VARCHAR(255),
    
    PRIMARY KEY(ROLE_ID)
);

INSERT INTO ROAD (UNIQUE_ROAD_IDENTIFIER, 
    ROAD_NAME, 
    DESCRIPTION, 
    LENGTH_IN_KILOMETERS,
    CATEGORY_ID,
    START_LOCATION_ID,
    END_LOCATION_ID)
VALUES ('R1', 'ROAD1', 'ROAD ONE', 1, 'C1', 'L1', 'L1');

INSERT INTO LOCATION (LOCATION_ID,
    LOCATION_NAME,
    LATITUDE,
    LONGITUDE,
    DESCRIPTION
)
VALUES ('L1', 'LOCATION', 100, 100, 'LOCATION ONE');


INSERT INTO PROJECT (PROJECT_CODE,
    PROJECT_NAME,
    DESCRIPTION,
    DATE_START,
    DATE_COMPLETE,
    ROAD_ID
)
VALUES ('P1', 'PROJECT1', 'PROJECT ONE', TO_DATE('2023-10-24', 'YYYY-MM-DD'), TO_DATE('2023-10-24', 'YYYY-MM-DD'), 'R1');
INSERT INTO PROJECT (PROJECT_CODE,
    PROJECT_NAME,
    DESCRIPTION,
    DATE_START,
    DATE_COMPLETE,
    ROAD_ID
)
VALUES ('P2', 'PROJECT2', 'PROJECT TWO', TO_DATE('2023-10-24', 'YYYY-MM-DD'), TO_DATE('2023-10-24', 'YYYY-MM-DD'), 'R2');


INSERT INTO CATEGORY(
    CATEGORY_ID,
    CATEGORY_NAME
    
)
VALUES ('C1', 'CATEGORY1');
INSERT INTO CATEGORY(
    CATEGORY_ID,
    CATEGORY_NAME
    
)
VALUES ('C2', 'CATEGORY2');
INSERT INTO CATEGORY(
    CATEGORY_ID,
    CATEGORY_NAME
    
)
VALUES ('C3', 'CATEGORY3');


INSERT INTO CONTRACT_MANAGER(
    MANAGER_ID,
    START_DATE_FOR_CONTRACT,
    END_DATE_FOR_CONTRACT,
    EMPLOYEE_ID
)
VALUES ('CM1', TO_DATE('2023-10-24', 'YYYY-MM-DD'), TO_DATE('2023-10-24', 'YYYY-MM-DD'), 'E1');

INSERT INTO CONTRACT(
    CONTRACT_NUMBER,
    CONTRACT_NAME,
    DESCRIPTION,
    ESTIMATED_COST,
    ACTUAL_COST,
    DATE_STARTED,
    DATE_ENDED,
    PROJECT_CODE,
    CONTRACTOR_COMPANY_NAME,
    CONTRACT_MANAGER_ID
)
VALUES ('C1', 'CONTACT1', 'CONTACT ONE', 1, 1,  TO_DATE('2023-10-24', 'YYYY-MM-DD'),  TO_DATE('2023-10-24', 'YYYY-MM-DD'), 'P1', 'COMPANY', 'CM1');



INSERT INTO STAFF_MEMBER(
    EMPLOYEE_ID,
    FIRST_NAME,
    LAST_NAME,
    DATE_FIRST_EMPLOYED,
    DATE_OF_BIRTH,
    GENDER,
    POSTAL_ADDRESS,
    CONTRACT_PHONE_NUMBER,
    EMAIL_ADDRESS
)
VALUES ('SM1', 'STAFF1', 'MEMBER1', TO_DATE('2023-10-24', 'YYYY-MM-DD'),  TO_DATE('2023-10-24', 'YYYY-MM-DD'), 'MALE', '100', '020000000', 'SM1@DOMAIN.COM');
INSERT INTO STAFF_MEMBER(
    EMPLOYEE_ID,
    FIRST_NAME,
    LAST_NAME,
    DATE_FIRST_EMPLOYED,
    DATE_OF_BIRTH,
    GENDER,
    POSTAL_ADDRESS,
    CONTRACT_PHONE_NUMBER,
    EMAIL_ADDRESS
)
VALUES ('SM2', 'STAFF2', 'MEMBER2', TO_DATE('2023-10-24', 'YYYY-MM-DD'),  TO_DATE('2023-10-24', 'YYYY-MM-DD'), 'MALE', '100', '020000000', 'SM2@DOMAIN.COM');
INSERT INTO STAFF_MEMBER(
    EMPLOYEE_ID,
    FIRST_NAME,
    LAST_NAME,
    DATE_FIRST_EMPLOYED,
    DATE_OF_BIRTH,
    GENDER,
    POSTAL_ADDRESS,
    CONTRACT_PHONE_NUMBER,
    EMAIL_ADDRESS
)
VALUES ('SM3', 'STAFF3', 'MEMBER3', TO_DATE('2023-10-24', 'YYYY-MM-DD'),  TO_DATE('2023-10-24', 'YYYY-MM-DD'), 'MALE', '100', '020000000', 'SM3@DOMAIN.COM');
INSERT INTO STAFF_MEMBER(
    EMPLOYEE_ID,
    FIRST_NAME,
    LAST_NAME,
    DATE_FIRST_EMPLOYED,
    DATE_OF_BIRTH,
    GENDER,
    POSTAL_ADDRESS,
    CONTRACT_PHONE_NUMBER,
    EMAIL_ADDRESS
)
VALUES ('SM4', 'STAFF4', 'MEMBER4', TO_DATE('2023-10-24', 'YYYY-MM-DD'),  TO_DATE('2023-10-24', 'YYYY-MM-DD'), 'MALE', '100', '020000000', 'SM4@DOMAIN.COM');
INSERT INTO STAFF_MEMBER(
    EMPLOYEE_ID,
    FIRST_NAME,
    LAST_NAME,
    DATE_FIRST_EMPLOYED,
    DATE_OF_BIRTH,
    GENDER,
    POSTAL_ADDRESS,
    CONTRACT_PHONE_NUMBER,
    EMAIL_ADDRESS
)
VALUES ('SM5', 'STAFF5', 'MEMBER5', TO_DATE('2023-10-24', 'YYYY-MM-DD'),  TO_DATE('2023-10-24', 'YYYY-MM-DD'), 'MALE', '100', '020000000', 'SM5@DOMAIN.COM');



INSERT INTO ROLE_(
    ROLE_ID,
    ROLE_NAME,
    DESCRIPTION
)
VALUES ('R_1', 'ROLE_1', 'ROLE_ ONE');
INSERT INTO ROLE_(
    ROLE_ID,
    ROLE_NAME,
    DESCRIPTION
)
VALUES ('R_2', 'ROLE_2', 'ROLE_ TWO');
